spring:
  application:
    name: datos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
  h2:
    console:
      enabled: true           # Habilita la consola web de H2
      path: /h2-console      # Ruta para acceder a la consola (http://localhost:8080/h2-console)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # create, create-drop, validate, update
    show-sql: true           # Muestra las consultas SQL en la consola

